Added `changeFile` function
squti/Android-Wave-Recorder pull request #10
Opened 2020-11-27 12:39 UTC by Andre-max

The new function changes the filePath only if the WaveRecorder has not yet started recording.
It also throws an IllegalStateException if called in the wrong state.

2020-11-27 17:49 UTC, squti requested changes
Please just commit WaveRecorder.kt file. Other files in the commit are unrelated to the issue.

2020-11-27 17:49 UTC, squti commented on android-wave-recorder/src/main/java/com/github/squti/androidwaverecorder/WaveRecorder.kt
> +            throw IllegalStateException("Cannot change filePath when still recording. Stop recording first then call this function.")
Please change the entire message to "Cannot change the file path during recording"

2020-11-28 21:27 UTC, squti commented
Please just rollback all of your changes and just make one commit for WaveRecorder.kt file and the make a new pull request. Moreover please use present tense in your commit message for example use Add instead of Added and consider my comment about the exception message.

2020-11-30 15:55 UTC, Andre-max commented
Sorry for the delay. I'm a beginner when it comes to Git so I couldn't find a way to revert a commit until today. Will pull in a short while.

2020-11-30 21:41 UTC, closed without merging